### ISSUE TITLE
Cannot `go get`

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rthornton128/goncurses#10]
```
```

$ go get -v code.google.com/p/goncurses
code.google.com/p/goncurses
# pkg-config --cflags form menu ncurses panel

Package form was not found in the pkg-config search path.
Perhaps you should add the directory containing `form.pc'
to the PKG_CONFIG_PATH environment variable
No package 'form' found
Package menu was not found in the pkg-config search path.
Perhaps you should add the directory containing`menu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'menu' found
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package panel was not found in the pkg-config search path.
Perhaps you should add the directory containing`panel.pc'
to the PKG_CONFIG_PATH environment variable
No package 'panel' found
exit status 1

```
```

Original issue reported on code.google.com by `peterbou...@gmail.com` on 10 Jun 2013 at 9:41

**Comment by BarisTuncer** [comment]
In fedora : sudo dnf install ncurses-devel
