### ISSUE TITLE
"Windows Users" section in the README is incomplete

### ISSUE THREAD

**Issue by ttaylorr** [rthornton128/goncurses#23]
In 0b9eb14d568638603cf85f480e273eb8fe701721, the README note to [Windows Users](https://github.com/rthornton128/goncurses/blob/0b9eb14d568638603cf85f480e273eb8fe701721/README.md#windows-users) trails off as incomplete saying:

```
Instead, Goncurses uses PDCurses which is not 100% compatible with ncurses. As a result,
```

The inclusion of the second part of the sentence that begins with "As a result..." would be useful!

**Comment by rthornton128** [comment]
Fixed. Thank you for bringing this to my attention!
