### ISSUE TITLE
Static Linking PDCurses

### ISSUE THREAD

**Issue by schancel** [rthornton128/goncurses#28]
This is a pretty nifty project.  Any thought about converting over to using static linking instead of a shared library to ease installation?

**Comment by rthornton128** [comment]
I haven't given it any thought to be honest. It certainly would help post-install. Perhaps best to provide instructions for static linking along side the shared library instructions and leave it up to the user?

**Comment by rthornton128** [comment]
Done some preliminary work on statically linking pdcurses.a (as well as vendoring pdcurses using git submodules) without avail. I have attempted several ways of static linking with cgo, including following the recommendation by Ian Taylor from this thread: https://groups.google.com/forum/#!msg/golang-nuts/H-NTwhQVp-8/i5vhUB5dZ5QJ.

Near as I can tell, they prefer cgo to use dynamic linking so we may be stuck with that.
