### ISSUE TITLE
examples/mouse

### ISSUE THREAD

**Issue by pdxjohnny** [rthornton128/goncurses#29]
When I click then press any key it produces this panic

```
john@john-laptop:mouse$ go run *.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x40bd66]

goroutine 1 [running]:
main.main()
	/home/john/Documents/go/src/github.com/rthornton128/goncurses/examples/mouse/mouse.go:89 +0xcb6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

https://github.com/rthornton128/goncurses/blob/master/examples/mouse/mouse.go#L89

System Details
---

go version go1.5 linux/amd64

Linux john-laptop 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I was just playing with it and thought someone else might have the same issue when really using it sometime.

**Comment by rthornton128** [comment]
It appears GetMouse has returned nil and accessing the coordinates require a dereference. Looking further, I think the code might better handle an error condition.

I'll look into it further.
