### ISSUE TITLE
Issue with examples/color/color.go

### ISSUE THREAD

**Issue by ahmetb** [rthornton128/goncurses#37]
I get this output when I run it:

![image](https://cloud.githubusercontent.com/assets/159209/21840992/3290be38-d795-11e6-8e8c-9023838704d3.png)

and when I press a key I get this:

![image](https://cloud.githubusercontent.com/assets/159209/21841006/3bb9d300-d795-11e6-87f1-91ec833683d4.png)

**Comment by rudis** [comment]
What output did you expect?

I think this is expected behavior and not a bug. It's mentioned in the source:
```
// Note that background doesn't just accept colours but will fill
// any blank positions with the supplied character too. Note that newly
// added text with spaces in it will have the blanks converted to the fill
// character, if given
stdscr.SetBackground(gc.Char('*') | gc.ColorPair(2))
```
