### ISSUE TITLE
Update wiki about KEY_RESIZE

### ISSUE THREAD

**Issue by gdm85** [rthornton128/goncurses#51]
I have been looking into #32 and #34 regarding the event `KEY_RESIZE` not firing.

I suggest adding this information to the wiki page KnownIssues (I do not have rights to do that).

A new approach that I found out to be working (despite Go's limitations with the signal handler) is to compile the Go program with `go build -buildmode=c-shared` and then link the `.so` file in a C program that handles the `getch()` loop.

`KEY_RESIZE` will then be synthesised correctly.

Cc @koojunho @wallnutkraken

**Comment by rthornton128** [comment]
Wiki has been updated.
